## Data Loading from kaggle-cli

In [2]:
! which python

/home/midori/Desktop/CraditCard_Fraud/.fraud_env/bin/python

In [3]:
%pip install kaggle

Collecting kaggle
  Using cached kaggle-2.0.0-py3-none-any.whl.metadata (15 kB)
Collecting bleach (from kaggle)
  Using cached bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting kagglesdk<1.0,>=0.1.15 (from kaggle)
  Using cached kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /home/midori/Desktop/CraditCard_Fraud/fraud_env/lib/python3.13/site-packages (from kaggle) (26.0)
Collecting protobuf (from kaggle)
  Using cached protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: python-dateutil in /home/midori/Desktop/CraditCard_Fraud/fraud_env/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Collecting python-slugify (from kaggle)
  Using cached python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting requests (from kaggle)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm (from kaggle)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting urllib3>=1.15.1 (from kaggle)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting webencodings (from bleach->kaggle)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: six>=1.5 in /home/midori/Desktop/CraditCard_Fraud/fraud_env/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Using cached text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting charset_normalizer<4,>=2 (from requests->kaggle)
  Using cached charset_normalizer-3.4.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (39 kB)
Collecting idna<4,>=2.5 (from requests->kaggle)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting certifi>=2017.4.17 (from requests->kaggle)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Using cached kaggle-2.0.0-py3-none-any.whl (75 kB)
Using cached kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached bleach-6.3.0-py3-none-any.whl (164 kB)
Using cached protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Using cached python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (195 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, text-unidecode, urllib3, tqdm, python-slugify, protobuf, idna, charset_normalizer, certifi, bleach, requests, kagglesdk, kaggle
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [kaggle]11/13 [kagglesdk]
Successfully installed bleach-6.3.0 certifi-2026.2.25 charset_normalizer-3.4.5 idna-3.11 kaggle-2.0.0 kagglesdk-0.1.16 protobuf-7.34.0 python-slugify-8.0.4 requests-2.32.5 text-unidecode-1.3 tqdm-4.67.3 urllib3-2.6.3 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
# # configuring the path of Kaggle.json file
# %mkdir -p ~/.kaggle
# %cp ../kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json

In [5]:
# API to fetch the dataset from Kaggle
! kaggle datasets download -d mlg-ulb/creditcardfraud -p ~/Desktop/CraditCard_Fraud/Data/

Dataset URL: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
License(s): DbCL-1.0
Downloading creditcardfraud.zip to /home/midori/Desktop/CraditCard_Fraud/Data
100%|██████████████████████████████████████| 66.0M/66.0M [00:09<00:00, 7.61MB/s]

In [ ]:
# extracting the compessed Dataset
from zipfile import ZipFile
from pathlib import Path

zip_path = Path.home() / "Desktop/CraditCard_Fraud/Data/creditcardfraud.zip" # zip file stored
extract_dir = Path.home() / "Desktop/CraditCard_Fraud/Data/" # .csv file needs to be extracted here

with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print("Dataset extracted to:", extract_dir)

Dataset extracted to: /home/midori/Desktop/CraditCard_Fraud/Data

## Data analysis

In [ ]:
import numpy as np
import pandas as pd

- The dataset contains transactions made by credit cards in September 2013 by European cardholders.
- This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.
- It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data.
- Features V1, V2, … V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'.
- Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset.
- Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.
- Given the class imbalance ratio, we recommend measuring the accuracy using the Area Under the Precision-Recall Curve (AUPRC). Confusion matrix accuracy is not meaningful for unbalanced classification.

In [2]:
dataset = pd.read_csv('../Data/creditcard.csv')
dataset.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [3]:
dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [4]:
dataset.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='str')

In [5]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
# distribution of legit transaction and fraudulent transaction
dataset.groupby('Class').size() # computes each group size size(Class == 0) and size(Class == 1)

Class
0    284315
1       492
dtype: int64

In [7]:
dataset.groupby('Class').count() # counts all the not null values in each columns

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,284315,284315,284315,284315,284315,284315,284315,284315,284315,284315,...,284315,284315,284315,284315,284315,284315,284315,284315,284315,284315
1,492,492,492,492,492,492,492,492,492,492,...,492,492,492,492,492,492,492,492,492,492

In [8]:
dataset['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

## Data preprocessing

In [9]:
# due to heighly imbalanec class values we need to seperate them for amalysis
legit = dataset[dataset.Class == 0]
fraud = dataset[dataset.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [11]:
# statistical measure of the data
legit.Amount.describe()
# precentile measures are also present
# ex. 25%ile of the transaction amount <= $5.65
#     50%ile of the transaction amount <= $22.00

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [14]:
# UNDER_SAMPLING

# no_of_fraudulent_transsaction = 492
# select randomly selected 492 tracsactions from legit_transaction
# ~1:1 ratio generated to remove class imbalance
legit_sample = legit.sample(n=500)

In [15]:
# concatenating two data frames
new_dataset = pd.concat([legit_sample,fraud],axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
133258,80311.0,-1.711438,1.391743,0.551974,1.271803,-0.358304,0.138687,-0.337978,1.108636,-0.509287,...,0.050080,0.287630,0.014783,0.013173,-0.036718,-0.236036,0.191254,0.095518,11.94,0
95695,65424.0,-1.005810,0.000625,2.890661,-1.086006,-0.651369,0.165343,0.085531,-0.005788,1.659486,...,-0.051374,0.370034,-0.257965,0.457380,-0.187992,0.726296,-0.352263,-0.078509,31.99,0
146654,87803.0,1.961440,-0.623093,-0.603060,0.211348,-0.437719,0.298097,-0.833600,0.247306,1.154521,...,0.210849,0.684447,0.111655,0.385389,-0.225814,0.585489,-0.041615,-0.056034,22.09,0
183928,126019.0,-0.543334,-1.779430,-5.050952,0.786994,-6.801502,4.315923,8.866539,-2.745370,-1.747921,...,0.722819,0.866732,1.521438,0.120230,-1.216927,0.233113,1.038456,-0.325022,1930.39,0
10786,18362.0,-0.707159,0.514761,2.312786,-1.922082,0.010925,-0.178972,0.394812,-0.233899,2.678143,...,-0.200783,-0.054076,-0.493423,-0.499350,0.562822,-0.803128,-0.213236,-0.164738,8.35,0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [18]:
new_dataset['Class'].value_counts()

Class
0    500
1    492
Name: count, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()
# the namture of the dataset has not change as mean values diff is same as before

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97577.162000,-0.001784,-0.043285,-0.029128,-0.139173,0.013328,0.017744,0.065585,-0.008320,0.031191,...,-0.038473,-0.005835,0.045172,-0.027913,-0.017662,0.001572,-0.010770,-0.040616,0.018700,90.043120
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [20]:
dataset.Amount.describe()

count    284807.000000
mean         88.349619
std         250.120109
min           0.000000
25%           5.600000
50%          22.000000
75%          77.165000
max       25691.160000
Name: Amount, dtype: float64

In [21]:
new_dataset.Amount.describe()

count     992.000000
mean      105.997510
std       249.201968
min         0.000000
25%         1.290000
50%        18.960000
75%        99.922500
max      2746.740000
Name: Amount, dtype: float64

## Splitting the dataset and train-test split

In [24]:
X = new_dataset.drop(columns='Class')
Y = new_dataset['Class']

In [25]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
133258,80311.0,-1.711438,1.391743,0.551974,1.271803,-0.358304,0.138687,-0.337978,1.108636,-0.509287,...,-0.081679,0.050080,0.287630,0.014783,0.013173,-0.036718,-0.236036,0.191254,0.095518,11.94
95695,65424.0,-1.005810,0.000625,2.890661,-1.086006,-0.651369,0.165343,0.085531,-0.005788,1.659486,...,-0.203863,-0.051374,0.370034,-0.257965,0.457380,-0.187992,0.726296,-0.352263,-0.078509,31.99
146654,87803.0,1.961440,-0.623093,-0.603060,0.211348,-0.437719,0.298097,-0.833600,0.247306,1.154521,...,-0.186810,0.210849,0.684447,0.111655,0.385389,-0.225814,0.585489,-0.041615,-0.056034,22.09
183928,126019.0,-0.543334,-1.779430,-5.050952,0.786994,-6.801502,4.315923,8.866539,-2.745370,-1.747921,...,-0.150083,0.722819,0.866732,1.521438,0.120230,-1.216927,0.233113,1.038456,-0.325022,1930.39
10786,18362.0,-0.707159,0.514761,2.312786,-1.922082,0.010925,-0.178972,0.394812,-0.233899,2.678143,...,-0.069985,-0.200783,-0.054076,-0.493423,-0.499350,0.562822,-0.803128,-0.213236,-0.164738,8.35

In [27]:
Y

133258    0
95695     0
146654    0
183928    0
10786     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 992, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.2,
                                                 stratify=Y,
                                                 random_state=22)

In [29]:
print(X_train.shape,X_test.shape)
print(Y_train.shape,Y_test.shape)

(793, 30) (199, 30)
(793,) (199,)

## Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=10000)

In [44]:
# training the model using training data
model.fit(X_train,Y_train,)

LogisticRegression(max_iter=10000)

## Evaluation

In [45]:
from sklearn.metrics import accuracy_score

# training data accuracy
X_train_predict = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_predict,Y_train)
print('Training accuracy score: ',training_data_accuracy)

Training accuracy score:  0.9558638083228247

In [48]:
# testing data accuracy
X_test_predict = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_predict,Y_test)
print('Training accuracy score: ',testing_data_accuracy)

# if the accuracy score trainign data >>> testing data --> overfitting
# if both training and testing accuracy <<< ---> underfitting

Training accuracy score:  0.9195979899497487